using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AspNetCoreDashboard.Generators
{
  [Generator]
  public sealed class UiModuleContentNamespaceGenerator : IIncrementalGenerator
  {
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
      var modules = context.SyntaxProvider
          .CreateSyntaxProvider(
              static (node, _) => node is ClassDeclarationSyntax,
              static (ctx, _) => GetModuleInfo(ctx))
          .Where(static info => info != null);

      context.RegisterSourceOutput(modules, static (spc, info) =>
      {
        var source = GenerateSource(info!);
        spc.AddSource($"{info!.ClassName}.ContentNamespace.g.cs", SourceText.From(source, Encoding.UTF8));
      });
    }

    private static ModuleInfo? GetModuleInfo(GeneratorSyntaxContext context)
    {
      var classDeclaration = (ClassDeclarationSyntax)context.Node;
      var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
      if (symbol == null || !ImplementsUiModule(symbol))
        return null;

      var pathPrefix = DerivePathPrefix(symbol.Name);
      var contentNamespace = symbol.Name + ".Content";

      var attribute = symbol.GetAttributes()
          .FirstOrDefault(a => a.AttributeClass?.Name == "UiModuleAttribute");
      if (attribute != null)
      {
        if (attribute.ConstructorArguments.Length > 0 &&
            attribute.ConstructorArguments[0].Value is string attrPrefix &&
            !string.IsNullOrEmpty(attrPrefix))
        {
          pathPrefix = attrPrefix;
        }

        foreach (var named in attribute.NamedArguments)
        {
          if (named.Key == "ContentNamespace" && named.Value.Value is string ns && !string.IsNullOrEmpty(ns))
            contentNamespace = ns;
        }
      }

      return new ModuleInfo(symbol.Name, symbol.ContainingNamespace.ToDisplayString(), pathPrefix, contentNamespace);
    }

    private static string GenerateSource(ModuleInfo info)
    {
      return $@"// <auto-generated />
namespace {info.Namespace}
{{
    partial class {info.ClassName}
    {{
        private const string GeneratedContentNamespace = ""{info.ContentNamespace}"";
        private const string GeneratedPathPrefix = ""{info.PathPrefix}"";
    }}
}}
";
    }

    private static string DerivePathPrefix(string className)
    {
      var suffix = "UiModule";
      var name = className.EndsWith(suffix, System.StringComparison.Ordinal)
          ? className.Substring(0, className.Length - suffix.Length)
          : className;

      if (string.IsNullOrEmpty(name))
        name = className;

      return "/" + name;
    }

    private static bool ImplementsUiModule(INamedTypeSymbol type)
    {
      return type.AllInterfaces.Any(iface =>
          iface.Name == "IUiModule" &&
          iface.ContainingNamespace?.ToDisplayString() == "AspNetCoreDashboard.Abstractions");
    }

    private sealed class ModuleInfo
    {
      public ModuleInfo(string className, string ns, string pathPrefix, string contentNamespace)
      {
        ClassName = className;
        Namespace = ns;
        PathPrefix = pathPrefix;
        ContentNamespace = contentNamespace;
      }

      public string ClassName { get; }
      public string Namespace { get; }
      public string PathPrefix { get; }
      public string ContentNamespace { get; }
    }
  }
}
