#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCoreDashboardLibrarySamples.Views.Dashboard
{
    using System;
    
    #line 5 "..\..\Views\Dashboard\Home.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Home : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\n\n");



WriteLiteral("\n\n");



            
            #line 6 "..\..\Views\Dashboard\Home.cshtml"
  
    //Layout = new _layout { Context = Context, Section = { ["Scripts"] = $"<script> var output = JSON.parse('{Raw(ViewData["ChartData"])}');</script> <script src='{Context.Options.PathMatch}/js.home.js'></script>" }, ViewData = ViewData };
    //var logs = (IEnumerable<ILogModel>)ViewData["Model"];


            
            #line default
            #line hidden
WriteLiteral("<script type=\"text/javascript\">\n\n</script>\n\n\n<div class=\"card\" style=\"margin-top:" +
" 3%\">\n    <div class=\"card-header bg-light\">\n        最近十条\n        <i class=\"fa f" +
"a-refresh\" onclick=\"loadList(1,10)\" style=\"float: right\"></i>\n    </div>\n    <di" +
"v class=\"card-body\" id=\"LogList\">\n        <div class=\"table-responsive\">\n       " +
"     <table class=\"table row mx-0\">\n                <thead class=\"w-100\">\n      " +
"              <tr class=\"row mx-0\">\n                        <th class=\"col-1\">Id" +
"</th>\n                        <th class=\"col-3\">Logger</th>\n                    " +
"    <th class=\"col-1\">级别</th>\n                        <th class=\"col-4\">消息</th>\n" +
"                        <th class=\"col-2\">时间</th>\n                        <th cl" +
"ass=\"col-1\">详情</th>\n                    </tr>\n                </thead>\n         " +
"       <tbody class=\"w-100\">\n     \n                </tbody>\n            </table>" +
"\n        </div>\n        <div class=\"modal fade show\" id=\"logInfoModal\" tabindex=" +
"\"-1\">\n            <div class=\"modal-dialog modal-lg\">\n                <div class" +
"=\"modal-content\">\n                    <div class=\"modal-header\">\n               " +
"         <h5 class=\"modal-title\">日志详情</h5>\n                        <button type=" +
"\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n                " +
"            <span aria-hidden=\"true\">×</span>\n                        </button>\n" +
"                    </div>\n                    <div class=\"modal-body\" id=\"logIn" +
"foBody\">\n\n                    </div>\n                </div>\n            </div>\n " +
"       </div>\n    </div>\n</div>");


        }
    }
}
#pragma warning restore 1591
